# Generated by Django 6.0.6 on 2026-06-24 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FuelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('ai92_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='АИ-92 остаток')),
                ('ai92_sold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='АИ-92 продажа')),
                ('ai95_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='АИ-95 остаток')),
                ('ai95_sold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='АИ-95 продажа')),
                ('dt_summer_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ДТ Лето остаток')),
                ('dt_summer_sold', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ДТ Лето продажа')),
                ('cash_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Наличные')),
                ('card_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Банк')),
                ('ведомость_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ведомость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accountant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Бухгалтер')),
            ],
            options={
                'verbose_name': 'Отчет АЗС',
                'verbose_name_plural': 'Отчеты АЗС',
            },
        ),
    ]
