# Generated by Django 6.0.6 on 2026-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_accountantprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuelreport',
            old_name='ведомость_sales',
            new_name='invoice_sales',
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Остаток ден. средств'),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='discount_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Скидка покупателям'),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='dt_euro_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ДТ Евро продажа'),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='dt_euro_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ДТ Евро остаток'),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='gas_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Газ продажа'),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='gas_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Газ остаток'),
        ),
        migrations.AddField(
            model_name='fuelreport',
            name='not_handed_shifts',
            field=models.IntegerField(default=0, verbose_name='Не сдано смен'),
        ),
    ]
