# Generated by Django 6.0.6 on 2026-06-26 19:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_rename_ведомость_sales_fuelreport_invoice_sales_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fuelreport',
            unique_together={('accountant', 'date')},
        ),
    ]
