# Generated by Django 6.0.6 on 2026-06-27 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_fuelreport_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelreport',
            name='dt_summer_sold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ДТ Евро Лето продажа'),
        ),
        migrations.AlterField(
            model_name='fuelreport',
            name='dt_summer_stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ДТ Евро Лето остаток'),
        ),
    ]
